import json
import os
from datetime import datetime
import traceback
from langchain_core.prompts import ChatPromptTemplate
from agents import validator_prompt, reporter_prompt, llm
from tools import match_data_cleaner, player_stats_cleaner, data_persistor

# ANSI Colors for Terminal Beautification
BLUE = "\033[94m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
MAGENTA = "\033[95m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

class ValorantPipelineWorkflow:
    def __init__(self):
        self.llm = llm
        self.history = []

    def _log_agent(self, step: str, name: str, input_data: str, output_data: str):
        """Helper to log steps in history and console with BEAUTIFUL truncation and JSON formatting."""
        
        def beautify(data_str, limit=5000):
            """Returns a pretty-printed, summarized version of the JSON for reports."""
            try:
                parsed = json.loads(data_str)
                # If it's a huge list, show the first item and the count
                if isinstance(parsed, list) and len(parsed) > 1:
                    count = len(parsed)
                    preview = json.dumps(parsed[0], indent=2)
                    return f"📋 [Showing 1 of {count} records]\n{preview}\n\n... (other records omitted for report clarity)"
                # If it's a huge dict, show it but cap the length
                pretty = json.dumps(parsed, indent=2)
                if len(pretty) > limit:
                    return pretty[:limit] + "\n\n... (truncated for report clarity)"
                return pretty
            except:
                s = str(data_str)
                return s[:limit] + ("..." if len(s) > limit else "")

        # Console Output (Uses more aggressive truncation for the screen)
        print(f"\n{BOLD}{MAGENTA}🤖 [STEP {step}] {name.upper()}{RESET}")
        print(f"{CYAN}📥 INPUT RECEIVED:{RESET}\n{BOLD}{beautify(input_data, 1000)}{RESET}")
        print(f"{GREEN}📤 OUTPUT PRODUCED:{RESET}\n{BOLD}{beautify(output_data, 1500)}{RESET}")
        print(f"{YELLOW}{'═'*60}{RESET}")

        # Report History (Uses slightly more generous limits but still condensed)
        self.history.append({
            "step": step,
            "agent": name,
            "timestamp": datetime.now().strftime("%H:%M:%S"),
            "input": beautify(input_data, 3000),
            "output": beautify(output_data, 3000)
        })

    def generate_report(self, final_status: str):
        """Generates a premium, transparent Hybrid Report (Programmatic Logs + AI Audit)."""
        report_filename = "AAA_REPORT_FOR_USER.md"
        
        # 1. Programmatic Log Generation (Transparent & Reliable)
        log_sections = []
        for entry in self.history:
            log_sections.append(
                f"### 🤖 [Step {entry['step']}] {entry['agent']}\n"
                f"- 🕒 **Time:** `{entry['timestamp']}`\n"
                f"- 📥 **INPUT DATA:**\n"
                f"```json\n{entry['input']}\n```\n"
                f"- 📤 **OUTPUT PRODUCED:**\n"
                f"```json\n{entry['output']}\n```\n"
                "\n---\n"
            )
        detailed_logs = "\n\n".join(log_sections)

        # 2. AI Audit Generation (High-Level Insight)
        summary_prompt = ChatPromptTemplate.from_template(
            "You are 'ReportSage', an Elite System Auditor.\n"
            "Final Status: {final_status}\n"
            "Key Metrics: {metrics}\n\n"
            "Write a brief (2-3 paragraph) Executive Summary and a 'System Health Audit' list (using emojis).\n"
            "Focus on high-level success or specific failure points.\n"
            "Do NOT output the raw logs, only the professional analysis."
        )

        try:
            metrics_summary = f"Steps: {len(self.history)}, Final Status: {final_status}"
            ai_response = (summary_prompt | self.llm).invoke({
                "final_status": final_status,
                "metrics": metrics_summary
            })
            ai_audit = ai_response.content
        except Exception as e:
            ai_audit = f"⚠️ AI Audit skipped: {str(e)}"

        # 3. Final Report Assembly (Premium Styling)
        full_report = f"""# 🌌 Aurora Pipeline: Audit Report

> [!IMPORTANT]
> **Final Status:** {final_status} | **Execution Time:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 📊 Executive Summary
{ai_audit}

## ⚙️ Detailed Execution Log
This section contains 100% transparent logs of every agent's input and output.

{detailed_logs}

---
*Report generated by Aurora LangChain Engine v2.0*
"""

        # Save the report
        try:
            target_path = os.path.join(os.getcwd(), report_filename)
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(full_report)
            
            # Show terminal info
            print(f"{BOLD}{YELLOW}📄 HYBRID REPORT GENERATED: {target_path}{RESET}")
            print(f"{CYAN}Open Link:{RESET} file:///{target_path.replace(os.sep, '/')}\n")
            
            return full_report
        except Exception as e:
            print(f"❌ Error saving report: {e}")
            return full_report

    def run(self, raw_matches: list):
        try:
            self.history = [] # Reset history
            
            print("\n" + "═"*60)
            print(f"{BOLD}{YELLOW}🚀 STARTING ENHANCED MULTI-AGENT PIPELINE{RESET}")
            print("═"*60)

            # STEP 1: CLEANING
            if isinstance(raw_matches, list):
                playable_matches = [m for m in raw_matches if m.get("is_available", True)]
                if not playable_matches:
                    print(f"\n{YELLOW}⚠️ [INFO] No playable matches found (all stubs). Pipeline stopped.{RESET}")
                    return {"status": "SKIPPED", "report": "No playable matches found after filtering stubs."}
                raw_matches = playable_matches

            raw_matches_json = json.dumps(raw_matches)
            cleaned_matches_json = match_data_cleaner.invoke({"raw_matches_json": raw_matches_json})
            self._log_agent("1", "CleanerBot", raw_matches_json, cleaned_matches_json)
            
            # STEP 2: ANALYST
            cleaned_player_stats_json = player_stats_cleaner.invoke({"raw_matches_json": raw_matches_json})
            self._log_agent("2", "AnalystBot", raw_matches_json, cleaned_player_stats_json)

            # STEP 3: VALIDATOR
            def safe_json_load(data_str, bot_name):
                try:
                    cleaned_str = data_str.strip()
                    if not (cleaned_str.startswith("{") or cleaned_str.startswith("[")):
                        return {"error": f"Bot {bot_name} did not return JSON.", "raw_output": data_str[:200]}
                    return json.loads(cleaned_str)
                except Exception as e:
                    return {"error": f"Failed to parse {bot_name} JSON: {str(e)}", "raw_output": data_str[:200]}

            validation_input = json.dumps({
                "match_data": safe_json_load(cleaned_matches_json, "CleanerBot"), 
                "player_stats": safe_json_load(cleaned_player_stats_json, "AnalystBot")
            }, indent=2)
            
            validation_response = (validator_prompt | self.llm).invoke({"cleaned_data": validation_input})
            val_content = str(validation_response.content)
            self._log_agent("3", "ValidatorBot (Gemini)", validation_input, val_content)

            if "data validated" in val_content.lower():
                # STEP 4: PERSISTENCE
                print(f"\n{BOLD}{CYAN}🤖 [STEP 4] Persistence Specialist...{RESET}")
                res1 = data_persistor.invoke({"data_json": cleaned_matches_json, "table_name": "matches"})
                res2 = data_persistor.invoke({"data_json": cleaned_player_stats_json, "table_name": "player_stats"})
                
                self._log_agent("4a", "Saving Matches", cleaned_matches_json, res1)
                self._log_agent("4b", "Saving Player Stats", cleaned_player_stats_json, res2)

                if "Error" in res1 or "Error" in res2:
                    final_status = "⚠️ COMPLETED WITH ERRORS"
                else:
                    final_status = "✅ SUCCESSFUL"
            else:
                final_status = f"❌ STALLED AT VALIDATION"

        except Exception as e:
            err_msg = str(e)
            print(f"\n{RED}❌ [DEBUG] PIPELINE CRASHED!{RESET}")
            traceback.print_exc()

            if "RESOURCE_EXHAUSTED" in err_msg or "429" in err_msg:
                final_status = "⚠️ QUOTA EXCEEDED"
            else:
                final_status = f"❌ FATAL ERROR"

        # Generate the report
        final_report = self.generate_report(final_status)
            
        print("═"*60 + "\n")
        return {"status": final_status, "report": final_report}

workflow = ValorantPipelineWorkflow()
